// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcStudent.Data;

namespace MvcStudent.Migrations
{
    [DbContext(typeof(MvcStudentContext))]
    [Migration("20200731010956_Renewal")]
    partial class Renewal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcStudent.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassroomId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Renewal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Vaccine1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vaccine2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vaccine3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vaccine4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vaccine5")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vaccine6")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Vaccine7")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
